apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: customer-self-service-backend
  name: customer-self-service-backend
spec:
  failedBuildsHistoryLimit: 1
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: customer-self-service-backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /customer-self-service-backend
    git:
      ref: master
      uri: https://github.com/hbenmansour/LakesideMutual
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:openjdk-8-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 1
  triggers:
  - generic:
      secretReference:
        name: lakeside-mutual-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: lakeside-mutual-github-webhook-secret
    type: GitHub
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/java@sha256:e6c06053ba4677acc8676765c727c93ae162c89888c1107dc91541de97025ff1
    type: ImageChange
  - type: ConfigChange
